[[DuckDB]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "099531c16771e67d462b2b5eb72338d6167c57c2"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "5303dc49e83c83694cf05eba1385b2593eab473d9b0d89e960f4da8fe5eddde1"
    url = "https://github.com/whatsthecraic/DuckDB_jll.jl/releases/download/DuckDB-v0.8.0+1/DuckDB.v0.8.0.aarch64-linux-gnu-cxx03.tar.gz"
[[DuckDB]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5b6173d30f9a75630e74f09de95e0b7861e6b315"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "c6213f123e1286947851e2bbcf5c6da12f6a8da4b3afdb8c2452162333f60ee2"
    url = "https://github.com/whatsthecraic/DuckDB_jll.jl/releases/download/DuckDB-v0.8.0+1/DuckDB.v0.8.0.aarch64-linux-gnu-cxx11.tar.gz"
[[DuckDB]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b653aabc690cef2cc1e116325ec2a33e3e33849e"
libc = "musl"
os = "linux"

    [[DuckDB.download]]
    sha256 = "a38c09b50930a358ba2821c36afd621ed00b6747b5b74b9465e3551f67c9e9fd"
    url = "https://github.com/whatsthecraic/DuckDB_jll.jl/releases/download/DuckDB-v0.8.0+1/DuckDB.v0.8.0.aarch64-linux-musl-cxx03.tar.gz"
[[DuckDB]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e6feae3d32018e42c5e05b00e1f67338c84f2f83"
libc = "musl"
os = "linux"

    [[DuckDB.download]]
    sha256 = "59850d105e774d23f0a2c275a1401b8a5fed11347f2a743237bce68fd6ab7a98"
    url = "https://github.com/whatsthecraic/DuckDB_jll.jl/releases/download/DuckDB-v0.8.0+1/DuckDB.v0.8.0.aarch64-linux-musl-cxx11.tar.gz"
[[DuckDB]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9e3cdd5758c2af8a9949f579941c701897d2d942"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "25cfc61325cf7075ccb220c58f0cfc560e7bf86faeff13b70888bdf71e233a76"
    url = "https://github.com/whatsthecraic/DuckDB_jll.jl/releases/download/DuckDB-v0.8.0+1/DuckDB.v0.8.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[DuckDB]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c9f3193b1d29a808249961343a0433f44634d2b1"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "667be722ec7a2c503be15d97c60d4d05217f27da2f319662d4eb2e2df0ab7d2c"
    url = "https://github.com/whatsthecraic/DuckDB_jll.jl/releases/download/DuckDB-v0.8.0+1/DuckDB.v0.8.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[DuckDB]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5072c39386b5edd0122a84e2f483652d7d6bbef5"
libc = "musl"
os = "linux"

    [[DuckDB.download]]
    sha256 = "3a0db960f9a051544302083f7619d4ba3628d00c9eeb7e6bc762458d7e173135"
    url = "https://github.com/whatsthecraic/DuckDB_jll.jl/releases/download/DuckDB-v0.8.0+1/DuckDB.v0.8.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[DuckDB]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b49bb315fa96f6fba836e3c219198b7b83a310ee"
libc = "musl"
os = "linux"

    [[DuckDB.download]]
    sha256 = "5a01ba1fe250c2f7242c07ec9f06fbafb39b50c82aa5ee41dc850350f9cf7238"
    url = "https://github.com/whatsthecraic/DuckDB_jll.jl/releases/download/DuckDB-v0.8.0+1/DuckDB.v0.8.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[DuckDB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bad1725606f7c1594f69a75141b59fa401361b04"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "9d36969a07fed4b85aed5c8b9f1854f52809193f95bf8696a8cb53f47d719e30"
    url = "https://github.com/whatsthecraic/DuckDB_jll.jl/releases/download/DuckDB-v0.8.0+1/DuckDB.v0.8.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[DuckDB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3658c596cabcd7e19a39e5cd292edd4ecd257324"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "43414610bfdcec5a91615d85593d6549ace46f04694550462080264171de3f75"
    url = "https://github.com/whatsthecraic/DuckDB_jll.jl/releases/download/DuckDB-v0.8.0+1/DuckDB.v0.8.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[DuckDB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c24280003b142946e7c3656562acf16ea85fe5cb"
libc = "musl"
os = "linux"

    [[DuckDB.download]]
    sha256 = "6c73265aa401654a9b5d744a1724149360fb2ab4c609bc585d60b40231ef4883"
    url = "https://github.com/whatsthecraic/DuckDB_jll.jl/releases/download/DuckDB-v0.8.0+1/DuckDB.v0.8.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[DuckDB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7e4fff068bdfc471c6cf74a304be6696f4c78e89"
libc = "musl"
os = "linux"

    [[DuckDB.download]]
    sha256 = "11729eeaf03b89877a98fecc7b9fe2b51cb3c49f169e065ae4a9a12c748af525"
    url = "https://github.com/whatsthecraic/DuckDB_jll.jl/releases/download/DuckDB-v0.8.0+1/DuckDB.v0.8.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[DuckDB]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ad5fe8b7823ba238b53a88edebe0536c2812363b"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "7f4e3d7f55b81683a18af5991b25f5821341496954e812e483afcced937b6bba"
    url = "https://github.com/whatsthecraic/DuckDB_jll.jl/releases/download/DuckDB-v0.8.0+1/DuckDB.v0.8.0.i686-linux-gnu-cxx03.tar.gz"
[[DuckDB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5d02ae972937e3fb93cb02f4a2b58ed5baec3756"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "9beb80b86ec3a43a0b66fe7a94eb545627ee38f7e510ec5840eabaeeb2207afc"
    url = "https://github.com/whatsthecraic/DuckDB_jll.jl/releases/download/DuckDB-v0.8.0+1/DuckDB.v0.8.0.i686-linux-gnu-cxx11.tar.gz"
[[DuckDB]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1c79697ef9df00bd8bc2b465dd9e49d3f31ecd79"
libc = "musl"
os = "linux"

    [[DuckDB.download]]
    sha256 = "d68be2f54fc38e241be877438fe5214e2fea01db2e32e0b9b4cd1a8954381345"
    url = "https://github.com/whatsthecraic/DuckDB_jll.jl/releases/download/DuckDB-v0.8.0+1/DuckDB.v0.8.0.i686-linux-musl-cxx03.tar.gz"
[[DuckDB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "48785568a6ef479834bf78a553a871d21c27443c"
libc = "musl"
os = "linux"

    [[DuckDB.download]]
    sha256 = "b003b3f8d1ec09c2d4fe277518e5278cc5ce0e2df6d238ffa3a03f9ae828a95a"
    url = "https://github.com/whatsthecraic/DuckDB_jll.jl/releases/download/DuckDB-v0.8.0+1/DuckDB.v0.8.0.i686-linux-musl-cxx11.tar.gz"
[[DuckDB]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "314d97a5643fa9b62f29188593eb688001e630f9"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "d8333f2a9db6a63fc32daa71f242c550ce20f6d65707e305c269c25f6f8a30c9"
    url = "https://github.com/whatsthecraic/DuckDB_jll.jl/releases/download/DuckDB-v0.8.0+1/DuckDB.v0.8.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[DuckDB]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "42e5efa2c8d07ccd8cb5d919f73f93697b3d5bbb"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "5be50dc9bff6fc08f1baf9139545e91888e921df75e8e53ed3b6765ab755f3f0"
    url = "https://github.com/whatsthecraic/DuckDB_jll.jl/releases/download/DuckDB-v0.8.0+1/DuckDB.v0.8.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[DuckDB]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "de4bed7e5024fd445bbdbd9f64e39d3a2c3eebbf"
libc = "musl"
os = "linux"

    [[DuckDB.download]]
    sha256 = "311abd8609ad5a93e9fe7db47f488008b32d556e8e88d11dcd5d26df6bfcff84"
    url = "https://github.com/whatsthecraic/DuckDB_jll.jl/releases/download/DuckDB-v0.8.0+1/DuckDB.v0.8.0.x86_64-linux-musl-cxx03.tar.gz"
[[DuckDB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5a6529f4c8e4f187b5e3c29fcb7ff1e3d493b7dd"
libc = "musl"
os = "linux"

    [[DuckDB.download]]
    sha256 = "737e5492101a3193b08aee6e2fde71caf364bbee80e3ad3e84ae43e377f35374"
    url = "https://github.com/whatsthecraic/DuckDB_jll.jl/releases/download/DuckDB-v0.8.0+1/DuckDB.v0.8.0.x86_64-linux-musl-cxx11.tar.gz"
[[DuckDB]]
arch = "x86_64"
git-tree-sha1 = "3d71dfaa48e0fe8eaf02538253d1d26fded33541"
os = "freebsd"

    [[DuckDB.download]]
    sha256 = "20bde616b3cae6e5545d4ee50136406c55e83bc8ae268f641edb03b7f377b58c"
    url = "https://github.com/whatsthecraic/DuckDB_jll.jl/releases/download/DuckDB-v0.8.0+1/DuckDB.v0.8.0.x86_64-unknown-freebsd.tar.gz"
[[DuckDB]]
arch = "aarch64"
git-tree-sha1 = "274f171a54e77334b245f6f0694b5220c2638a20"
os = "macos"

    [[DuckDB.download]]
    sha256 = "7cb3ccc211badf62bb840fc6a4f9f94095d413f9b46f08956a2fedd72bab7490"
    url = "https://github.com/whatsthecraic/DuckDB_jll.jl/releases/download/DuckDB-v0.8.0+1/DuckDB.v0.8.0.aarch64-apple-darwin.tar.gz"
[[DuckDB]]
arch = "x86_64"
git-tree-sha1 = "18b671d16bef2bd08e591e2106a09d2c2c9e5ed8"
os = "macos"

    [[DuckDB.download]]
    sha256 = "30605ea4e080879e131cee4e07c9ec3f2876d48b5d9cee1ad6e11d1bed09c8d4"
    url = "https://github.com/whatsthecraic/DuckDB_jll.jl/releases/download/DuckDB-v0.8.0+1/DuckDB.v0.8.0.x86_64-apple-darwin.tar.gz"
[[DuckDB]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "27704cdb34abbeafc3bf6ae07a64369b7c6533b8"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "1fc6b5552eeb92c92c2012538cdc03adfda11a1d5c37d1b9d0c269504c9dbae6"
    url = "https://github.com/whatsthecraic/DuckDB_jll.jl/releases/download/DuckDB-v0.8.0+1/DuckDB.v0.8.0.x86_64-linux-gnu-cxx03.tar.gz"
[[DuckDB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "07e374c225ab75e3f4cdda49dd0c9fe5e83fd3e3"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "d079a1dc8d83f3ab8c8e7c6bfa296666a4ae2450e44c783e128d7d99a373ae55"
    url = "https://github.com/whatsthecraic/DuckDB_jll.jl/releases/download/DuckDB-v0.8.0+1/DuckDB.v0.8.0.x86_64-linux-gnu-cxx11.tar.gz"
[[DuckDB]]
arch = "aarch64"
git-tree-sha1 = "59e88e02cd17d6a046373300a2e8129bad7fd003"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "be8e157c9198d65391501066d565a7f90b3f7b1ca6d226b6522d5af66b49d9c1"
    url = "https://github.com/whatsthecraic/DuckDB_jll.jl/releases/download/DuckDB-v1.0.0+1/DuckDB.v1.0.0+1.aarch64-linux-gnu.tar.gz"
